### ISSUE TITLE
relicense under Apache 2.0?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-collection-laws#24]
just like e.g. https://github.com/scala/scala-xml/pull/242 and https://github.com/scala/scala-parser-combinators/pull/184

@Ichoran any objection?

**Comment by SethTisue** [comment]
ping @Ichoran, can I go ahead and do this?

**Comment by SethTisue** [comment]
ping @Ichoran

**Comment by Ichoran** [comment]
@SethTisue - :+1:   Apache 2 is fine.

**Comment by SethTisue** [comment]
I moved this copyright notice from the old LICENSE file into the new NOTICE file:

```
Copyright (c) 2014-2019, Ichoran
```

but it seems a little iffy. would it be okay if I changed it to a Lightbend copyright? or to "Rex Kerr"?

**Comment by Ichoran** [comment]
Yeah, Lightbend copyright is fine.  Or Rex Kerr.  I'm not sure why I thought Ichoran was a good thing to put in the copyright, but I'm pretty sure there are more Rex Kerrs than Ichorans.  Anyway, this stuff is really Lightbend's.

**Comment by SethTisue** [comment]
thanks Rex! 361082902cf15017123f20699118019da1c6b423
